const userName = document.getElementById('name')
const email = document.getElementById('email')
const subject = document.getElementById('subject')
const msg = document.getElementById('message')
const form = document.getElementById('contact-form')
const btn = document.getElementById('submit')
form.addEventListener('submit', (e)=>{
    e.preventDefault()
    if(userName.value === '') alert('Please Enter your Name First')
    if(!isNaN(userName.value)) alert('Please Enter A valid Name')
    if(email.value === '') alert('Please Enter Email Address')
    if(!isNaN(subject.value)) alert('Please Enter a valid Subject')
    if(msg.value === '') alert('Please Enter Message first') 
})